@BASE_URL =  http://localhost:8080/api/v1/

### Auth try in browser
GET {{BASE_URL}}auth/google

# It will redirect to the callback after the consent screen
# http://localhost:8080/api/v1/auth/google/callback?code=4{randomid}&scope=email+profile+openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email&authuser=0&prompt=consent

# Response
{
"statusCode": 200,
"data": {
"_id": "67c23df43d6364772dd8ba25",
"email": "hidaytrahman@gmail.com",
"firstName": "Hidayt",
"lastName": "Rahman",
"picture": "https://lh3.googleusercontent.com/a/ACg8ocJVjbgEVF0gu-TdkatqPOUqRu052_fSeBHMIpuoJGAIlVwu2b8PNg=s96-c",
"accessToken": "achestokasoao",
"createdAt": "2025-02-28T22:51:32.884Z",
"updatedAt": "2025-02-28T22:51:32.885Z",
"__v": 0
},
"message": "User successfully authenticated"
}


# Get Statas
### Login
GET {{BASE_URL}}auth/status
credentials: 'include'